source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'Incognito.xcodeproj'
platform :ios, '8.0'
use_frameworks!                   # [1] use dynamic frameworks

pod 'AeroGearOAuth2'              # [2] use latest AeroGearOAuth2 version 
