source 'https://github.com/CocoaPods/Specs.git'
 
xcodeproj 'Incognito.xcodeproj'
platform :ios, '8.0'
use_frameworks!
 
#pod 'AeroGearOAuth2', :git => 'https://github.com/aerogear/aerogear-ios-oauth2.git'
pod 'OAuthSwift', '0.5.2'